### ISSUE TITLE
Remediate example sketches to make them more universal and approachable

### ISSUE THREAD

**Issue by moxondesign** [TeensyAudio/Wavetable-Synthesis#1]
Arduino 1.8.1 TeensyDuino 1.3.6 
Teensy3.2 Model

region "FLASH" overflowed by 295350 bytes?
Maybe this only works on the larger Teensy3.6 & 3.6?

Some setup instructions in the Example would be useful.
Things like "Select Tools -> USB -> MIDI", etc.
would be helpful for first-time users.

**Comment by beroberobaa** [comment]
Hi,

Yes, while I didn't create that sketch personally, the issue is assuredly that it was created and tested only with the 3.6 in mind. I'll look to cleaning up the examples to make them more universal and intuitive once I get around to posting some updates.

**Comment by moxondesign** [comment]
Thanks. I'm just starting to work with the library, so if you like, I'll give some feedback on what is clear and what needs examples, clarification, etc..  Great Job though - the basic example worked right away on the Teensy 3.2 model

**Comment by beroberobaa** [comment]
Yeah, if you have any feedback, I'd be happy to hear; it's kind of difficult to get a sense for what doesn't work usability-wise in the library when you're already aware of where everything is.

**Comment by Muiota** [comment]
Hello, is it possible to store the generated PCM-data files on the SD and dynamically load them?

**Comment by beroberobaa** [comment]
@Muiota I'm afraid not, not without semi significant changes to the library at least

**Comment by moxondesign** [comment]
@Muiota - you can use Audacity or www.swamiproject.org to do that - usually as output as .wav files,
which the regular Teensy Audio library can read from SDcard  ;-) Tom
